# Generated by Django 4.1.3 on 2022-11-18 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=7)),
                ('phone_no', models.CharField(max_length=14)),
                ('country', models.CharField(max_length=10)),
                ('dob', models.DateField(null=True)),
                ('age', models.PositiveIntegerField(default=0, editable=False)),
                ('dp', models.ImageField(default='default.png', upload_to='Profile-pics/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('name', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('blogger', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-posted'],
            },
        ),
    ]
